from importlib import import_module
from genaipf.conf.server import PLUGIN_NAME

# 不需要登陆态的接口元组
PATH_WITHOUT_LOGIN = (
    '/v1/api/sendVerifyCode',
    '/v1/api/userLogin',
    '/v1/api/userLoginOther',
    '/v1/api/plugin/login',
    '/v1/api/userCheckExist',
    '/v1/api/register',
    '/v1/api/getCaptcha',
    '/v1/api/testVerifyCode',
    '/v1/api/sendEmailCode',
    '/v1/api/modifyPassword',
    '/v1/api/sendChat',
    '/v1/api/getMessageList',
    '/v1/api/getMsgGroupList',
    '/v1/api/sendStreamChat',
    '/v1/api/sendChat',
    '/v1/api/sendOneshotChat',
    '/v1/api/sendRawChatStream',
    '/v1/api/sendStylizedRequest',
    '/v1/api/getShareMessages',
    '/v1/api/pay/cardInfo',
    '/v1/api/pay/callback',
    '/v1/api/addFeedback',
    '/v1/api/pay/account',
    '/v1/api/assistantChat',
    '/v1/api/getAssistantHistory',
    '/v1/api/tw/feedback',
    '/v2/api/sendVerifyCode',
    '/v2/api/userLogin',
    '/v2/api/userLoginOther',
    '/v2/api/plugin/login',
    '/v2/api/userCheckExist',
    '/v2/api/register',
    '/v2/api/getCaptcha',
    '/v2/api/testVerifyCode',
    '/v2/api/sendEmailCode',
    '/v2/api/modifyPassword',
    '/v2/api/sendChat',
    '/v2/api/getMessageList',
    '/v2/api/getMsgGroupList',
    '/v2/api/sendStreamChat',
    '/v2/api/sendChat',
    '/v2/api/sendOneshotChat',
    '/v2/api/sendRawChatStream',
    '/v2/api/sendStylizedRequest',
    '/v2/api/getShareMessages',
    '/v2/api/pay/cardInfo',
    '/v2/api/pay/callback',
    '/v2/api/addFeedback',
    '/v2/api/pay/account',
    '/v2/api/assistantChat',
    '/v2/api/getAssistantHistory',
    '/v2/api/sendAppEmailCode',
    '/v2/api/tw/feedback',
)

if PLUGIN_NAME:
    plugin_submodule_name = f'{PLUGIN_NAME}.routers.without_login'
    plugin_submodule = import_module(plugin_submodule_name)
    without_login = plugin_submodule.WITHOUT_LOGIN
    PATH_WITHOUT_LOGIN = PATH_WITHOUT_LOGIN + without_login